### ISSUE TITLE
Travis integration pls

### ISSUE THREAD

**Issue by trufae** [radare/radare2-bindings#149] opened 2017-02-23 17:46 UTC
on every r2 commit to see if we break the vapis

**Comment by trufae** [comment] 2017-02-23 17:46
cc @Maijin

**Comment by Maijin** [comment] 2017-02-23 18:00
Need API token from this r2-b repo to do that see https://docs.travis-ci.com/user/triggering-builds

**Comment by XVilka** [comment] 2019-02-25 09:03
Duplicate of https://github.com/radare/radare2-bindings/issues/167

**Closed by XVilka** 2019-02-25 09:03 UTC
